apiVersion: apps/v1
kind: Deployment
metadata:
  name: frauddetectservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frauddetectservice
  template:
    metadata:
      labels:
        app: frauddetectservice
    spec:
      containers:
      - name: frauddetectservice
        image: frauddetectservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/frauddetectdb?useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root