apiVersion: v1
kind: Service
metadata:
  name: notificationservice-service
spec:
  selector:
    app: notificationservice
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
